### ISSUE TITLE
Изучить работу с роутингом в Laravel

### ISSUE THREAD

**Issue by vitek999** [MDKP2020/Noskin#15]
Как результат создать маршрутизацию для приложения

Таблица запрсоов: https://docs.google.com/document/d/1pPBlE81DVa1fsc-oTY9llc6MiXBYICDdvecYzny0iZk/edit?usp=sharing

**Comment by unterumarmung** [comment]
В официальной документации неплохо описана работа с роутингом
https://laravel.com/docs/8.x/routing
