### ISSUE TITLE
Спроектировать схему БД

### ISSUE THREAD

**Issue by vitek999** [MDKP2020/Noskin#20]
Спроектировать схему бд, предусмотрев возможность переводов людей между курсами и привязку группы к году обучения.

Резултат: https://github.com/MDKP2020/Noskin/wiki/%D0%A1%D1%85%D0%B5%D0%BC%D0%B0-%D0%91%D0%94

**Comment by unterumarmung** [comment]
![Схема БД](https://user-images.githubusercontent.com/39276703/93919025-3f3c8b00-fd1e-11ea-85e8-ef6995821389.png)
`year` - курс обучения (1, 2, 3, 4 - бакалавриат/специалитет, 5 - специалитет, 1, 2 - магистратура).
`groups` - состав групп на каждом курсе (ИВТ-161 на первом курсе, ИВТ-365 - на третьем, и т. п.).
`student_history` - история обучения студента - в какой группе в каком году был. 
`students` описывает каждого студента.

**Comment by marieower** [comment]
1. Нет иерархии (факультет/кафедра/направление)
2. Проблема с переводом между курсами: если переводить группы в неправильном порядке, то они сливаются
3. Подумать над изменением названия группы при переходе на другой курс (уточнить у Д.В.)

**Comment by unterumarmung** [comment]
![Схема БД](https://user-images.githubusercontent.com/39276703/94137820-1cbe8500-fe78-11ea-962a-8aa93ceb9355.png)

## Таблица `possible_groups`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `groups`
* `start_date` хранит дату начала существования группы
* `end_date` хранит дату завершения существования группы (расформирована, отчислена в связи с окончанием обучения)
* `grade` хранит текущий курс группы

## Таблица `students_to_group`
* `start_date` хранит дату зачисления студента в группу
* `end_date` хранит дату отчисления/перевода студента из группы
* `target` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

**Comment by marieower** [comment]
possible groups -> group patterns

**Comment by unterumarmung** [comment]
![image](https://user-images.githubusercontent.com/39276703/94138660-81c6aa80-fe79-11ea-9b76-bc253f1db87a.png)

## Таблица `group_patterns`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `groups`
* `start_date` хранит дату начала существования группы
* `end_date` хранит дату завершения существования группы (расформирована, отчислена в связи с окончанием обучения)
* `grade` хранит текущий курс группы

## Таблица `students_to_group`
* `start_date` хранит дату зачисления студента в группу
* `end_date` хранит дату отчисления/перевода студента из группы
* `target` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

**Comment by unterumarmung** [comment]
![Схема БД](https://user-images.githubusercontent.com/39276703/95018208-4002e480-066f-11eb-9fa3-537f73edbdbe.png)


## Таблица `group_patterns`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `groups`
* `start_date` хранит дату начала существования группы
* `end_date` хранит дату завершения существования группы (расформирована, отчислена в связи с окончанием обучения)
* `grade` хранит текущий курс группы

## Таблица `students_to_group`
* `start_date` хранит дату зачисления студента в группу
* `end_date` хранит дату отчисления/перевода студента из группы
* `next_group` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

## Таблица `expel_reason`
Хранит возможные причины отчисления.

**Comment by unterumarmung** [comment]
![Схема БД](https://user-images.githubusercontent.com/39276703/95018208-4002e480-066f-11eb-9fa3-537f73edbdbe.png)


## Таблица `group_patterns`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `groups`
* `start_date` хранит дату начала существования группы
* `end_date` хранит дату завершения существования группы (расформирована, отчислена в связи с окончанием обучения)
* `grade` хранит текущий курс группы

## Таблица `students_to_group`
* `start_date` хранит дату зачисления студента в группу
* `end_date` хранит дату отчисления/перевода студента из группы
* `next_group` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

## Таблица `expel_reason`
Хранит возможные причины отчисления.

**Comment by unterumarmung** [comment]
![image](https://user-images.githubusercontent.com/39276703/95021084-f5d62f00-067f-11eb-8c71-e87283ed4e45.png)

## Таблица `group_patterns`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `groups`
* `start_date` хранит дату начала существования группы
* `end_date` хранит дату завершения существования группы (расформирована, отчислена в связи с окончанием обучения)
* `grade` хранит текущий курс группы

## Таблица `students_to_group`
* `start_date` хранит дату зачисления студента в группу
* `end_date` хранит дату отчисления/перевода студента из группы
* `next_group` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

## Таблица `expel_reason`
Хранит возможные причины отчисления.

**Comment by marieower** [comment]
Группе нужен признак, отчислена ли в текущем году

**Comment by unterumarmung** [comment]
![image](https://user-images.githubusercontent.com/39276703/95436100-83599d80-0964-11eb-85a5-9fb6ac8d6094.png)

## Таблица `group_patterns`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `academic_years`
Хранит учебные года. 

## Таблица `groups`
Представляет группу.

## Таблица `groups_to_years`
Представляет группу в конкретном учебном году. Хранит её курс в указанный год.

## Таблица `students_to_group`
* `start_year` хранит год зачисления студента в группу
* `end_year` хранит год отчисления/перевода студента из группы
* `next_group` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

## Таблица `expel_reason`
Хранит возможные причины отчисления.

**Comment by unterumarmung** [comment]
![image](https://user-images.githubusercontent.com/39276703/96347945-4acd6880-10b6-11eb-87b1-51e85e578bbb.png)
## Таблица `group_patterns`
В поле `pattern` хранятся возможные варианты названия групп. Например `ПрИн-*67`, вместо `*` подставляется курс.

## Таблица `students`
Хранит информацию о студентах

## Таблица `academic_years`
Хранит учебные года. 

## Таблица `groups`
Представляет группу.

## Таблица `groups_to_years`
Представляет группу в конкретном учебном году. Хранит её курс в указанный год.

## Таблица `students_to_group`
* `start_year` хранит год зачисления студента в группу
* `end_year` хранит год отчисления/перевода студента из группы
* `next_group` хранит ссылку на группу, в которую был переведён студент, если отчислен, то значение `null`

## Таблица `expel_reason`
Хранит возможные причины отчисления студента.

## Таблица `group_expel_reason`
Хранит возможные причины отчисления группы.

## Таблица `majors`
Хранит направления обучения.

**Comment by marieower** [comment]
так как студента можно отчислять N раз за 1 год, в student_to_group year поменять на date

**Comment by marieower** [comment]
добавить студенту признак "отчислен", чтобы выбирать студентов, доступных для зачисления в новую группу

**Comment by unterumarmung** [comment]
![image](https://user-images.githubusercontent.com/39276703/96845124-65f6fa00-1461-11eb-969b-21b3ac775402.png)
